### ISSUE TITLE
Remove mapbox references in docs

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-style-spec#111]
There are some places that still link to the `mapbox://` protocol and use some example that has the `mapbox` name in them.
All of these should be replaced with mapblire and http(s):// protocol.

**Comment by HarelM** [comment]
Assigning S bounty
Bounty direction: https://github.com/maplibre/maplibre/issues/191

**Comment by typebrook** [comment]
Hi @HarelM, Can I work on this?

Also, Is this issue just related to current repo? Or we need to check other maplibre repos too?

**Comment by HarelM** [comment]
This bounty is just for this repo.
Go ahead!

**Comment by typebrook** [comment]
@HarelM 
PR is made. Besides docs page, I also remove **test cases** and **migration step** which are related to Mapbox API. Let's have further discuss in PR page.

**Comment by typebrook** [comment]
@HarelM Based on [Step-by-Step Bounties Guide][link]
> Post a link to the invoice on the GitHub issue.

https://opencollective.com/maplibre/expenses/138358

[link]: https://maplibre.org/roadmap/step-by-step-bounties-guide/#3-claiming-a-bounty
