### ISSUE TITLE
Design Proposal: Update text-offset to better support variable anchor placement

### ISSUE THREAD

**Issue by drwestco** [maplibre/maplibre-style-spec#112]
# Design Proposal: Update text-offset to better support variable anchor placement

## Motivation

`text-offset` and `text-radial-offset` both seem tailored to placement of labels around a center-anchored icon. For pushpins, teardrops, or other asymmetrical icons, There's no style syntax to distribute labels evenly around the icon's perimeter.

Existing style properties are all based on the anchor position (yellow circle); since text and icon are independent, and may even be on completely separate layers, there's no correlation with the bounds of the icon.

e.g., if the desired label placements for all eight `variable-anchor` positions are as follows, what's the best way to indicate this through the symbol layer style? The icon is anchored at the bottom (yellow circle indicates anchor), so the desired `text-offset` for `'left'` vs `'bottom-left'` would have a different y value.

![image](https://user-images.githubusercontent.com/743030/231822869-bb86def4-4247-439b-8d9c-49e013cdc39f.png)

The existing style properties have some capability, but are not sufficient to fully cover scenarios like these. In the examples below, to simplify the diagram and explanation, we'll just consider text placement in the four cardinal directions.

Using `"text-radial-offset: 1`, the nearest edge of the text is placed 1em away from the anchor. i.e., when the left or right text anchor is chosen, the offset is outward by 1em in the X direction; when the top or bottom text anchor is chosen , the offset is outward by 1em in the Y direction. Thus `text-radial-offset` is best for circular, square, or other icon shapes where width == height.

![image](https://user-images.githubusercontent.com/743030/231814489-2246c02a-59a9-412b-a309-94f5ee622104.png)

When used with `text-variable-anchor`, `text-offset` gives flexibility to specify the outward shift independently for the X and Y axes. A value like `"text-offset": [1.5, 6]` lets us fix the icon/text overlap when the top slot ("Anchor: bottom") is chosen. Since the offset is always outward relative to the anchor (not the icon center), it adversely affects the bottom slot ("Anchor: top"). So `text-offset` is best for symmetric icons, where the icon is centered over the anchor.

![image](https://user-images.githubusercontent.com/743030/231817496-00c5bd8d-2c2b-4e76-b022-7dc40746268c.png)

One solution using existing style properties is to use both the `text-offset` and `text-translate` style properties. By selecting the appropriate values, it is possible to improve the distribution of labels around the icon. Here, `"text-offset": [2.2, 3.5]` and `text-translate: [0, -38]` produce the desired result. However, since `text-translate` is a paint property, collisions aren't properly considered. If another symbol occupies the same space as the translated label, there will be an unavoidable overlap.

![image](https://user-images.githubusercontent.com/743030/231820596-dbd19e6d-a2f0-4bd7-9afb-03d3166ce44c.png)

## Proposed Change

** Updated following voting results **

### Point

A point is a two-element array of numbers, representing an [x, y] coordinate pair. Units and other interpretation of the x/y values depend on where and how the point type is used.

### text-variable-anchor-offset

_Layout property. Optional array, alternating enum and point values._

To increase the chance of placing high-priority labels on the map, you can provide an array of text-anchor locations, each paired with an offset value. The renderer will attempt to place the label at each location, in order, before moving on to the next location+offset. Use text-justify: auto to choose justification based on anchor position.

The length of the array must be even, and must alternate between enum and point entries. i.e., each anchor location must  be accompanied by a point, and that point defines the offset when the corresponding anchor location is used. Positive offset values indicate right and down, while negative values indicate left and up. Anchor locations may repeat, allowing the renderer to try multiple offsets to try and place a label using the same anchor.

When present, this property takes precedence over text-anchor, text-variable-anchor, text-offset, and text-radial-offset.

Example

```JSON
{
  "text-variable-anchor-offset": ["top", [0, 4], "left", [3, 0], "bottom", [1, 1]]
}
```

When the renderer chooses the `top` anchor, [0, 4] will be used for `text-offset`; the text will be shifted down by 4 ems. When the renderer chooses the `left` anchor, [3, 0] will be used for `text-offset`; the text will be shifted right by 3 ems.

## API Modifications

Existing code that processes `variable-anchor` during symbol placement + layout needs to be updated to check and prefer the new property.

## Migration Plan and Compatibility

Current behavior+syntax for `text-variable-anchor` and `text-offset` will be preserved. 

New behavior is opt-in. If `text-variable-anchor-offset` is present, it supersedes the other offset/anchor properties. The other offset/anchor properties may still be included in the style, to support other clients. Note that any clients that validate style on load will throw an error when encountering an unfamiliar property, so styles using `text-variable-anchor-offset` may not be supported by such older clients. 

## Rejected Alternatives

See discussion thread here: https://github.com/maplibre/maplibre-gl-js/discussions/1832
and here: https://github.com/maplibre/maplibre-gl-js/discussions/2029

**Comment by HarelM** [comment]
Looks good to me. Thanks for the detailed explanation!
@louwers @ovivoda @wipfli any objections or more info needed here?
I vote for approving this.

**Comment by ovivoda** [comment]
@HarelM this looks good to me. Implementation wise, how will this be done? First on JS then we will try to have it working also in native?

**Comment by drwestco** [comment]
@ovivoda Yeah, I'm ready to start the JS implementation. We have some design goals in Azure+Bing to take advantage of this.

**Comment by HarelM** [comment]
@ovivoda any platform can start the implementation, it depends on the driving force I guess...

**Comment by wipfli** [comment]
Looks good to me.

**Comment by wipfli** [comment]
@drwestco if you implement this in MapLibre GL JS, please also add an example to the docs website.

**Comment by HarelM** [comment]
I first and foremost would like to apologise for re-opening this design proposal.
I would like to thanks @drwestco for all the hard work around this and his patience as well.
When I first read this, it made a lot of sense. After reviewing the code and understanding how this will truly affect the style specification it occurred to me that this specification is a bit complex to "get right", it's also super powerful on the other hand.
The problem I see, is the same as any problem with two arrays - that you need to make sure they are aligned - both have the same number of items and that the items are not mixed.
For the example above it's easy to get it right, but for an array of 8 items, it's harder (also to read it, not just write it):
```ts
{
    "text-offset": [[0, 4], [3, 0], [1, 1], [2, 3], [0,0]], // did I get it right?
    "text-variable-anchor": ["top", "left", "bottom", "right", "top-left", "top-right"]
}
```
Creating a large object with anchor-position to offset map is also complicated in terms of writing, but eliminates the arrays sync issue, but this map would "feel" weird in the style as I don't think we have something similar.

It occurred to me after reading this again, that there might be an easier solution, less powerful though, I think:
`anchor-offest` (or something similar, feel free to change the name) - a new layout property.
Setting the anchor offset moves the entire calculation of the anchor of the text to a new location, and everything is calculated from this point.
For icons that are symmetric but not centered, you can set an offset only in `x` and `y=0`. for asymmetric Icons you can find the bounding rectangle, and find its center to set the anchor offset.
Yes, it won't allow you to place the text in a star like placement, but I think it's a lot simpler.
It might not be a good solution, and if this is the case, then I think @drwestco current PR should be accepted.

```ts
{
    "anchor-offset": [2,3],
    "text-variable-anchor": ["top", "left", "bottom", "right", "top-left", "top-right"] // this doesn't change but it will move the text around the new anchor position
}
```

Thanks, and sorry again.

**Comment by wipfli** [comment]
Good point, @drwestco.

Instead of using two properties with arrays, could we have one property where we mix the two array?

For example, instead of writing:

```js
{
    "text-offset": [[0, 4], [3, 0], [1, 1]], 
    "text-variable-anchor": ["top", "left", "bottom"]
}
```

Could we do this:
```js
{
  "text-offset": ["top", [0, 4], "left", [3, 0], "bottom", [1, 1]]
}
```

**Comment by wipfli** [comment]
Maybe we could use a name like `text-offset-array` or so, which requires the `text-offset` and `text-variable-anchor` not to be set or so...

**Comment by HarelM** [comment]
To summarize the options for the discussion today in the TSC:
1. new single property to move the anchor called `text-anchor-offset`
```ts
{
    "text-anchor-offset": [2,3],
    "text-variable-anchor": ["top", "left", "bottom", "right", "top-left", "top-right"] // this doesn't change but it will move the text around the new anchor position
}
```
2. extend `text-offset` with an ability to be an array of offsets for the variable anchor:
```ts
{
    "text-offset": [[0, 4], [3, 0]],
    "text-variable-anchor": ["top", "left"]
}
```
3. A compound array with a new property name `text-offset-array` or extend one of the existing ones: `text-offset` or `text-variable-anchor`
```ts
{
  "text-offset": ["top", [0, 4], "left", [3, 0], "bottom", [1, 1]] // or
  "text-offset-array": ["top", [0, 4], "left", [3, 0], "bottom", [1, 1]] // or
  "text-variable-anchor": ["top", [0, 4], "left", [3, 0], "bottom", [1, 1]]
}
```

**Comment by HarelM** [comment]
Option 2: extend `text-offset` with an ability to be an array of offsets for the variable anchor:
```ts
{
    "text-offset": [[0, 4], [3, 0]],
    "text-variable-anchor": ["top", "left"]
}
```
Need to verify that this doesn't cause a crash when used with older versions.

**Comment by HarelM** [comment]
Option 3: A compound array that extend `text-offset`
```ts
{
  "text-offset": ["top", [0, 4], "left", [3, 0], "bottom", [1, 1]] // or
}
```
Need to verify that this doesn't cause a crash when used with older versions.

**Comment by HarelM** [comment]
Option 4: A compound array with a new property name `text-offset-array`
```ts
{
  "text-offset-array": ["top", [0, 4], "left", [3, 0], "bottom", [1, 1]]
}
```

**Comment by HarelM** [comment]
Option 5: A compound array that extend `text-variable-anchor`
```ts
{
  "text-variable-anchor": ["top", [0, 4], "left", [3, 0], "bottom", [1, 1]]
}
```
Need to verify that this doesn't cause a crash when used with older versions.

**Comment by HarelM** [comment]
I'll post it on slack, feel free to vote. 
I'll verify what happens in the next days in web when setting the above options for existing properties. 
@louwers can you check what happens in native please?

**Comment by louwers** [comment]
@HarelM Could you give an example style?

**Comment by wipfli** [comment]
I voted with a :+1: for the `text-offset-array` option

**Comment by drwestco** [comment]
I get a similar error, and the entire layer is rejected, when using a new property instead of modifying an existing.  `Error: layers.poi-labels.layout.text-anchor-offset: unknown property "text-anchor-offset"`. I can't remember what happens when an error like this is encountered when loading an entire style, instead of just a single layer via `addLayer` - it may reject the entire style if validation isn't turned off.

**Comment by ambientlight** [comment]
I would go for Option 4, I think we should aim to have the style spec updates resulting in superset, whenever possible.

though `text-offset-array` is not super descriptive by itself, I would maybe think of something like `text-variable-anchor-offset`

**Comment by HarelM** [comment]
I've just tested and if there's a layer that is not valid in the middle of the style, the entire style fails to load if the style is set (as opposed to a addLayer).
I would recommend a new property then and not update an existing one due to this behavior.

**Comment by drwestco** [comment]
Won't the same style rejection occur when an old client encounters a new property? At least, gl-style-validate spits out an error in this case:
```
% gl-style-validate style.json
style.json:49: layers[0].layout.text-variable-anchor-offset: unknown property "text-variable-anchor-offset"

**Comment by HarelM** [comment]
Yes, you are right, it doesn't matter if this is a new property or an updated one... :-/

**Comment by HarelM** [comment]
We will review this item in the next TSC meeting which will be at June 14th.
Whoever would like to vote should do it until then.

**Comment by jonahadkins** [comment]
👍

**Comment by HarelM** [comment]
@louwers do you need to open an issue in the native repo to track this?
This is basically designed and published.

**Comment by HarelM** [comment]
@louwers any updates on the above question?

**Comment by louwers** [comment]
I have created a tracking issue (see link above this comment).

I have also made a PR that allows tracking parity in the documentation: https://github.com/maplibre/maplibre-style-spec/pull/644

**Comment by louwers** [comment]
Note that [variableAnchorOffsetCollection](https://maplibre.org/maplibre-style-spec/layers/variableAnchorOffsetCollection.md) is a dead link in the documentation.

https://maplibre.org/maplibre-style-spec/layers/?h=variableanchoroffsetcollection#text-variable-anchor-offset
