### ISSUE TITLE
Make .tar distribution for MapLibre Native

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-style-spec#121]
Per the Native TSC meeting April 12th 2023, it would make sense to distribute only the v8.json, and all the 300 expression tests (.json files) as a github release .tar to be consumed in MapLibre Native.

This would allow MapLibre Native to remove the copies of these files, and give a common foundation to GL JS and Native.

**Comment by HarelM** [comment]
What would be the solution for the web in this case? download this as part of the `prepare`? get it from the npm package itself?
I generally don't object to keeping the json files in this repo as they basically well define the behavior of the style spec through acceptance criterial using examples.

**Comment by HarelM** [comment]
Is this now simpler?
Also I think that when creating a release all the code in the repo gets zipped and uploaded to the release page in github so it Native should be able to download it as needed.
See here:
https://github.com/maplibre/maplibre-style-spec/releases/tag/v20.0.0
Let me know if there's anything else needed to be done as part of this issue.
CC: @louwers

**Comment by birkskyum** [comment]
It is definitely easier with the tests migrated here already

**Comment by louwers** [comment]
Yes, this can be closed. It contains source code that is not relevant for Native, but that is manageable.

Follow-up issue. https://github.com/maplibre/maplibre-native/issues/940
