### ISSUE TITLE
Creation of new Style Spec Docs

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-style-spec#126]
There are many reasons to abandon the existing docs, but mainly we need proper typescript support. [MapBox Batfish](https://github.com/mapbox/batfish) only supports javascript, and while it forces us to do a ton of workarounds we still end up with bugs like https://github.com/maplibre/maplibre-gl-js-docs/issues/421 due to lacking ts support. 

This task covers creating a docs site with feature parity to the existing Style Spec section found at maplibre.org/maplibre-gl-js-docs/style-spec/, but using a much more modern stack, and below is the reasoning for the selected stack:

## Selection of stack

This describes the reasoning behind the selected stack used for the style-spec docs, which is based on Solid / SolidStart.

### What is the style spec ?

**1. The style spec json**
The style-spec is in it's essense a .json document, currently at v8.x, thus it can be found at `v8.json`.  It contains all the style parameters, and for each parameter it has information about:

* the parameter type
* from which version each sdk added support for this property
* config for expressions
* default value
* text for the docs
* if the parameter is required/optional

**2. Metadata for the style-spec**
In order to read and document this json document of properties, it's necessary to know some things about it, such as the allowed types for each field. For instance, the parameter type, here it's good to know what potential types exist. For the expression config, when an expression like `step` or `interpolate` is mentioned, is has data about input and output types, as well as arguments, and allowed comparison signatures (`'==', '!=', '<', '<=', '>', '>='`). Currently, this style-spec data is found in typescript files located at:

* ./src/ - See `compound_expression`, `expression/definitions/index.tsx`, `expression/types.ts`
* ./docs/ - See `item.tsx`, `expression-metadata.tsx`

Even though each platform (gl js, gl native) in principle should be treated equal, the docs need a verison of the metadata to be built, and because both the docs and MapLibre GL JS are web based, this typescript version is used. MapLibre Native also has an inplementation of the same metadata, but it's to be found in the maplibre-gl-native repository.

### How to build the docs?
We used pre-compiled static site generation to build the docs, because it allow us at not cost to deploy oru docs as GitHub Pages, and it performs well too. Conventional popular options here are:

* Hugo (go)
* MkDocs (python)
* Jekyll (ruby)
* Hexo (js)
* Slate (ruby)
* Docusaurus (js)

Because we use the MapLibre GL JS metadata implementation in TypeScript, and thus have to run some typescript logic in order to generate the markup, any of the options that are relying on other languages are suddenly no-ops, limiting our options to the likes of:

* Docusaurus (MDX)
* Next.js (React)
* Gatsby (React)
* Remix (React)
* Qwik City (Qwik) (Vite based)
* Astro (Astro/MDX as entrypoint + Agnostic embed) (Vite based)
* SolidStart (Solid) (Vite based)
* VitePress (Vue) (Vite based)
* SvelteKit (Svelte) (Vite based)

It's of course desireable to use MDX or another markdown extentions langauge, because it's easy readable on GitHub. While the JSX components included in MDX can be generated dynamically at build time, the markdown itself is surprisingly difficult to generate, and in our case where we use a lot fo the data from the v8.json in the markup, this becomes problematic. Preliminary tests of Astro and Docusaurus here showed that in particular code snippets proved to be problematic, because a code snipped in markdown is designated with triple backticks \`\`\`. Inside of this code block it's impossible to include variables like example urls from `v8.json` and versions from `package.json` using the common syntax of `{varname}` - the variable names will simply be written out in plain text. This blocks us from using a tool like Docusaurus for now.

* Next.js (React)
* Gatsby (React)
* Remix (React)
* Qwik City (Qwik) (Vite based)
* Astro (Astro as entrypoint + Agnostic embed) (Vite based)
* SolidStart (Solid) (Vite based)
* VitePress (Vue) (Vite based)
* SvelteKit (Svelte) (Vite based)

In order to avoid further complexity, I think we should keep our code as plain typescript files, reducing our options further to:

* Next.js (React)
* Gatsby (React)
* Remix (React) (Vite based)
* Qwik City (Qwik) (Vite based)
* SolidStart (Solid) (Vite based)

Either of these options could have worked for us. I decided not go with Qwik, because their focus is on loading in only the needed js when interacting with each component on a page (thus delaying running js to the very last moment), which is the polar opposite to our usecase which is SSG where as much as possible of the work is done up front. Regarding Solid and React, they have a near identical syntax, but Solid has a much higher performance. SolidStart on isn't as mature as Solid yet, but it's merely a small addon built on top of the very stable and popular ViteJS, and my preliminary tests showed that it could do all that we needed well - and knowing that we could easily fall back to one of the alternatives I ended up selecting it:

* **SolidStart (Solid)**

As a side note on a bright future, SolidStart will from the next version 0.3.0 use the popular SSG module from Astro (also on top of Vite), and thus stabilize our solution further so we don't use an experimental engine for that. This change will most likely only touch the vite.config.ts.

**Comment by birkskyum** [comment]
Closed by #88

**Comment by wipfli** [comment]
Thanks for the summary, @birkskyum
