### ISSUE TITLE
layer `ref` property not well documented

### ISSUE THREAD

**Issue by rotu** [maplibre/maplibre-style-spec#213]
`LayerSpecification` objects can have a `ref` property which, if defined, makes the layer inherit properties from another layer.

This is not documented on https://maplibre.org/maplibre-style-spec/layers/ and makes it hard to typecheck a `LayerSpecification` (e.g. since `type` is a mandatory property in all the `LayerSpecification` subtypes).

Maybe this should be documented. Maybe this behavior should be deprecated.

https://github.com/maplibre/maplibre-style-spec/blob/2c7a6217748de89a23dedb41c16506303213ba40/src/deref.ts#L24-L37

Additionally:
1. The `derefLayers` function is defined as taking an `Array<Layer>` type, though `Layer` is not a type.
2. The `ref` property does not work transitively (i.e. a grandchild layer might not properly inherit properties from its grandparent, depending on the order of the layers)
3. If a layer contains both a `ref` and a heritable property like `maxzoom`, the value of that heritable property is clobbered by the parent value. This is surprising.

**Comment by HarelM** [comment]
I tend to say this should be deprecated, but it's worth bringing this up in the next TSC meeting.

**Comment by maxammann** [comment]
I actually believe if it was never documented that it can just be removed instead of deprecating it.

Not sure about its usage though.

**Comment by 1ec5** [comment]
`ref` was once documented in v7, but v8 turned it into an implementation detail; it isn’t to be used by style authors: mapbox/mapbox-gl-js#1393. Among other things, style diffing does not respect this property, so it’s a recipe for breakage in ordinary GL JS usage: mapbox/mapbox-gl-style-spec#486.

**Comment by HarelM** [comment]
I also see that it was planned to be removed in version 9, which was never published.
Bottom line, use it at your own risk, preferably, don't use it.
