### ISSUE TITLE
Version management of Maplibre style spec

### ISSUE THREAD

**Issue by JinIgarashi** [maplibre/maplibre-style-spec#214]
Regarding #188, #213, other proposed style issues and issues previously implemented, it is better to think about the way of version management of maplibre style spec.

I just realized both are still using `version: 8` since some of new features on style spec are already incompatible each other. Mapbox also added new feature with same version 8, and Maplibre too. I am not sure exactly which version of maplibre style spec is fully compatible with Mapbox style.

- Maplibre style spec doc
https://maplibre.org/maplibre-style-spec/root/#version

- Mapbox style spec doc
https://docs.mapbox.com/mapbox-gl-js/style-spec/root/#version

Furthermore, currently both Maplibre and Mapbox does not archive previous version of style spec in their websites. However, it is good to think about having archiving previous version of style spec rather than only supporting the latest one.

Maplibre style spec can be used by Mapbox users, on the other hand, Mapbox style spec can also be used by Maplibre users. It can be important to make sure how the versions of style spec are managed if Maplibre is going to different future from Mapbox.

**Comment by HarelM** [comment]
The general version is generally not interesting, what you would be interested in is each property support matrix. This will tell you which version of native and web support which feature.
This applies to both mapbox and maplibre.
There's no real value in keeping old versions of the docs site (this is not true to maplibre-gl-js obviously).

**Comment by JinIgarashi** [comment]
@HarelM Thank you for the comment. Sure, it would be nice if there is such support matrix for each property of style spec. If so, archiving previous versions of style doc might not be important.

By the way, I just realized by reading CHANGELOG.md of mapbox style spec, the version of style.json itself was initially synchronized with the repository's version, but Mapbox started not using it since v9. I don't know why.

https://github.com/mapbox/mapbox-gl-js/blob/main/src/style-spec/CHANGELOG.md#800

If the version of style-spec source code and style.json have same meaning, it would be nice to identify the supported software version easily.

Maplibre and Mapbox share same spec until v13.7, and then they started using different versioning. Maplibre started with v14 (v19.27 is the latest), and Mapbox still continue using v13 (v13.27 is the latest).

Maybe considering starting synchronizing again between style-spec code version and style JSON's version can be a nice idea for future reference.

**Comment by HarelM** [comment]
Closing this for now as I don't see an actual action item I can draw from this discussion.
If there's something more specific please let me know and I'll consider opening this issue again.
