### ISSUE TITLE
Create contributor guide for maplibre-style-spec

### ISSUE THREAD

**Issue by ZeLonewolf** [maplibre/maplibre-style-spec#236]
There is currently no contributor guide for maplibre-style-spec. A contributor guide should cover the steps needed to establish a development environment where a contributor can develop and test a PR which has changes in both maplibre-style-spec and gl-js (or native). I've tried `npm link` and `npm install <local folder>` approaches to set up a multi-project environment and have failed after multiples hours of attempts and much debugging.  I would happily offer to write up steps if I could figure it out myself :grimacing:

**Comment by HarelM** [comment]
While I agree a contribution guide is needed, I usually look at the CI code when I'm not sure:
`nvm install` to get the right node version
`npm install` to install packages
`npm run build` to build
`npm run test-unit` to run the tests.

I've just verified that this works on a clean ubuntu environment with codespaces here at gihub.
Let me know if you need help making things work.
If you work on windows, try using wsl if it fails on windows, but I'm not sure there's something special here that should fail...

**Comment by HarelM** [comment]
Yeah, that requires a bit in depth knowledge of how to do that with npm and stuff, my go to in this situation is usually to simply copy the dist of style-spec to the node_modules folder of maplibre-gl in the right place.
There is also a possibility to create a local package and npm install it in maplibre-gl, I think it's a bit more complex, but considered "safer".
But these instructions are not specific to maplibre, it's generally correct for javascript development.
Nevertheless, Feel free to add a developer guide, it certainly can't hurt to have this info here as well... :-)
