### ISSUE TITLE
Clarify interpretation of the in expression

### ISSUE THREAD

**Issue by mvarendorff** [maplibre/maplibre-style-spec#322]
The docs on the [deprecated filter expressions](https://maplibre.org/maplibre-style-spec/deprecations/#other-filter) state (emphasis mine):

> Though **filters defined with this syntax will continue to work**, we recommend using the more flexible [expression](https://maplibre.org/maplibre-style-spec/expressions/) syntax instead.

In case of an expression `["in", "foo", "bar"]`, how is determined whether to interpret this as the deprecated or recommended syntax, i.e. whether `"foo"` is understood as property key or a literal?

**Comment by HarelM** [comment]
I'm not sure, but I **think** there is an attempt to upgrade the style before parsing it to convert these deprecated filters to expressions and then use them regularly.
But I'm not sure, you can test and see what's the outcome of trying this out.

**Comment by HarelM** [comment]
Old syntax is using string while new syntax is using arrays.
If you write `["==", "one", "two"]` it will always return false in new syntax, so this is automatically converted to old syntax where `one` should be a property of a `feature`.
I've just rewritten the docs and it should be fairly easy to change the file here to better explain the issue:
https://github.com/maplibre/maplibre-style-spec/blob/c74b5030cf1749e00958f6ba1617e5019837e976/docs/deprecations.md

I'm not sure I know how to improve the explanation, feel free to submit a PR to better explain what you understand.

The source of this is the following code I believe, which determines if the expression is an "old" filter expression or not:
https://github.com/maplibre/maplibre-style-spec/blob/c74b5030cf1749e00958f6ba1617e5019837e976/src/feature_filter/index.ts#L47

**Comment by mvarendorff** [comment]
Alright, neat, thanks! Yeah, that makes a lot of sense, I never really thought about that the result is always a fixed value if both arguments are interpreted as literals... The code reference also helped lots! Closing this because it's been sufficiently answered (and the docs are fairly clear on second and third glance)!
