### ISSUE TITLE
Style Spec Design Proposals

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-style-spec#33]
I think it would be great to have a place for design proposals that target the style spec and with that all supported platforms of the MapLibre rendering engines.

For example, we could start designing better writing system support by agreeing on a design proposal here in this repo. The design proposal could have the same format as the one in the native repo, e.g. https://github.com/maplibre/maplibre-gl-native/pull/580

What do you think?

**Comment by 1ec5** [comment]
How large or small of a change to the style specification should require a design proposal in this repository, versus an ordinary issue?

**Comment by wipfli** [comment]
Good question @1ec5. I am not sure. Maybe we could say if an implementation takes more than say 40 hours one should do a design proposal?

**Comment by HarelM** [comment]
Since the style spec is a cross platform concern, I think every change to the style spec should start with a design so that both native and web (and maybe later on something else) can influence the decision and process, and contribute.
There's a lot of moving parts when taking about the style spec and so we need a large audience to make sure we cover as much as we can up front.

**Comment by wipfli** [comment]
I agree @HarelM. Let's just make a design proposal for every style spec change. Like that it is also easier for everyone to understand what is needed when contributing.

**Comment by wipfli** [comment]
I guess then we are good to go. You want ro change something cross platform, then make a design proposal here.

**Comment by 1ec5** [comment]
Should this expectation be documented somewhere in the repository for discoverability before closing out this issue?

**Comment by HarelM** [comment]
I think it should, also the readme needs a lot of TLC... see #5 ...

**Comment by wipfli** [comment]
Right...

**Comment by HarelM** [comment]
This is somewhat covered in the main readme.
If the current readme is not clear enough, please simply open a PR.
Closing...
