### ISSUE TITLE
Design Proposal: New 'sprites' property to handle multiple sprite urls within a style

### ISSUE THREAD

**Issue by geolives** [maplibre/maplibre-style-spec#378]
## Motivation

The goal is to allow multiple sprites urls within a style.
Sometimes you want to merge 2 styles into a single big style that contains all layers from the 2 styles you want to merge.
If these styles got different sprites, you need to rebuild to a single big sprite to do so that isn't practical.

It'll lead into some practical interest to allow dividing sprite generation into smaller sprites instead of one big chunk.

## Proposed Change

Add a new property `sprites` in the root of the style to be an array of multiple strings representing sprite urls.
This new property overloads the `sprite` property for implementations that supports it.

In order to keep image renderers to be fast, keep them into the same logic of hashmap to store image identifiers.
That means if multiple sprites wants to use the same image identifiers, keep the first occurence and drop any duplicates.

## API Modifications

We can expect some new API methods for implementations, like :
- `addSpriteUrl()`
- `removeSpriteUrl()`

I cannot forecast the performance cost of a change this magnitude while manipulating a style on a functional map renderer.
When a sprite is ready, it'll be needed to reload all layers that use images on them to update if applicable. Perhaps this isn't a good thing to allow, and it's simply better to forbid to change the sprite urls on-the-fly.

## Migration Plan and Compatibility

The new property `sprites` will be only supported for implementations that can handle it. For other implementations, it'll be ignored.
That way, renderers can check for `sprites` property if they allow loading multiple sprites, and use the `sprite` property if they cannot.

## Rejected Alternatives

The current alternative to that is to generate a new sprite that merges the two sprites in either each merging style. If the sprite is already big, that could leads to very huge files to download. Moreover, the process is slow.

Some equivalent in Mapbox exist about this kind of feature, but without improvements within the last years.

**Comment by HarelM** [comment]
I believe this is already implemented in maplibre web...
https://github.com/maplibre/maplibre-style-spec/blob/9edeb22907d6017ca856a816df4b71cd35d9e21a/src/reference/v8.json#L87

**Comment by HarelM** [comment]
This is the relevant PR for web:
https://github.com/maplibre/maplibre-gl-js/pull/1805

**Comment by geolives** [comment]
And I guess I found this one for native, but still in progress:
https://github.com/maplibre/maplibre-native/issues/641

I'm sorry for the duplicate so.

**Comment by wipfli** [comment]
@geolives do you think the docs need to be improved in this area?

**Comment by geolives** [comment]
I guess it's ok.
I read docs again and it's clearly specified.
