### ISSUE TITLE
define type for GeoJSONSourceSpecification data

### ISSUE THREAD

**Issue by cyrfer** [maplibre/maplibre-style-spec#393]
# Design Proposal: Define type for GeoJSONSourceSpecification data

### General
Developers expect their IDEs to help them write what is needed, often aided by the type system of a package.
If a developer attempts to use a package and gets undesired results, they go looking for solutions in various places (SO, Github, etc), making them less productive.
A well managed type system is critical for developer experience.

### Practical
When attempting to reproduce the following demo,
https://maplibre.org/maplibre-gl-js/docs/examples/multiple-geometries/

...in a modern (Typescript, React) development environment, the sources and layers are not producing an expected visual result. There is no confirmation that `data` or `data.features` are correct because of the use of the `unknown` type for `data`. It becomes one more thing that needs to be verified. Useful typing could avoid that rabbit hole.

```javascript
const sourceId = `source-location-fences-project-${projectId}`
console.log('fences: adding source ' + sourceId)
map.addSource(sourceId, {
  type: 'geojson',
  // HELP NEEDED HERE, DEVELOPERS ARE FLYING BLIND
  data: {
    type: 'FeatureCollection',
    features: locations.map(loc => ({
      type: 'Feature',
      geometry: loc.fence,
    }))
  }
})
const layerId = `layer-location-fences-project-${projectId}`
console.log('fences: adding layer ' + layerId)
map.addLayer({
  id: layerId,
  type: 'fill',
  source: sourceId,
  paint: {
      'fill-color': '#888888',
      'fill-opacity': 0.4
  },
})
```

The type system for `source.data` shows `unknown`, which provides no value for a developer.

## Proposed Change

Improve the type used for `source.data` from `unknown` to `FeatureCollection` from `@types/geojson`.

### Outstanding Questions
1. I do not currently know which [rollup configuration](https://github.com/maplibre/maplibre-style-spec/blob/main/rollup.config.ts) produces the the types.
2. I do not currently know what source file is responsible for the following exported type visible in the `dist/index.d.ts` file.

```
export type GeoJSONSourceSpecification = {
	"type": "geojson";
	"data": unknown;
	"maxzoom"?: number;
	"attribution"?: string;
	"buffer"?: number;
	"filter"?: unknown;
	"tolerance"?: number;
	"cluster"?: boolean;
	"clusterRadius"?: number;
	"clusterMaxZoom"?: number;
	"clusterMinPoints"?: number;
	"clusterProperties"?: unknown;
	"lineMetrics"?: boolean;
	"generateId"?: boolean;
	"promoteId"?: PromoteIdSpecification;
};
```

## API Modifications

No run-time changes. The contract will be better communicated via the improved type.

## Migration Plan and Compatibility

Bump the version number. This feels like a minor version bump to me.

The functionality and feature will be the same, but now users abusing the (previously unstated) contract may see transpile errors.

## Rejected Alternatives

No known alternatives for improving current developer experience.

**Comment by HarelM** [comment]
It's not an easy solution.
The types are generated from the v8.json file in this repo.
The v8.json file defines a proprietary definition language which is not strong enough to represent this.
There was an effort to migrate this to json-schema, but it's not that easy too, as the expression definition is very complicated.

Bottom line, feel free to poke around the generate-typings script and see if you can solve this specific issue, or invest more time in finding a replacement for this proprietary system 😕

**Comment by HarelM** [comment]
I'll see if I can somehow alter the code generation code to facilitate for this.

**Comment by HarelM** [comment]
@cyrfer do you have a good way to test this?
I've edited the code in the `generate-sytle-spec.ts` file to fix this issue specifically, but I'm not sure how to test if my code is correct or not...

**Comment by cyrfer** [comment]
@HarelM I would simply check the developer experience when using that interface. Most developers would assume the IDE would provide hints when typing.

[Here is an example project](https://stackblitz.com/edit/react-maplibre-layer-issue?file=src%2FApp.tsx). Lines 66-69 of App.tsx use the interface. You could comment them out and write `data:` and see what the IDE prompts you with.

```javascript
    data: {
      type: 'FeatureCollection',
      features,
    }
```

I think you would need to point the project dependencies at your feature branch or release. Feel free to fork that demo. Warning, it might not be worthy of production distribution.

**Comment by HarelM** [comment]
My initial check shows that it's working as expected, once a new version is released you will be able to check it as well.
