### ISSUE TITLE
Add to Taginfo Projects

### ISSUE THREAD

**Issue by danieldegroot2** [maplibre/maplibre-style-spec#402]
Show the OpenStreetMap community what [data](https://wiki.openstreetmap.org/wiki/Tags) you are using. Add your project to the [list](https://taginfo.openstreetmap.org/projects) of [Taginfo Projects](https://github.com/taginfo/taginfo-projects).

**Comment by HarelM** [comment]
There is nothing specific to OSM in this library.
Also it's widely uses OSM data, there's a processing that needs to be done in order use OSM tags and convert it to mvt format.

**Comment by danieldegroot2** [comment]
https://github.com/streetcomplete/streetcomplete-mapstyle/issues/146#issuecomment-1783009547
Is there a specification similar to openmaptiles? See https://github.com/openmaptiles/openmaptiles/issues/1269

**Comment by HarelM** [comment]
Openmaptiles is one of those mentioned processed, yes.
