### ISSUE TITLE
Two different SDK support tables for one item

### ISSUE THREAD

**Issue by zstadler** [maplibre/maplibre-style-spec#458]
**Describe the bug**
[Raster DEM source volatile attribute](https://maplibre.org/maplibre-style-spec/sources/#raster-dem-volatile) has two different SDK support tables:

![image](https://github.com/maplibre/maplibre-style-spec/assets/1304610/661d9242-8376-49e8-bab3-70b4754b4223)

**Comment by HarelM** [comment]
Thanks for letting us know! This will be fixed shortly.
