### ISSUE TITLE
Freshly built style-spec is incompatible with maplibre-gl-js

### ISSUE THREAD

**Issue by sbachinin** [maplibre/maplibre-style-spec#474]
Maplibre-gl-js still imports **operations** from maplibre-style-spec. (https://github.com/maplibre/maplibre-gl-js/blob/main/src/style/style.ts#L20C84-L20C95).

But recently operations were removed from style-spec code. (https://github.com/maplibre/maplibre-style-spec/commit/9eaffbd37e1acd53c79a96818dcf6f4c8f2aba62)
This change is not yet reflected in the published style-spec bundle so everything works fine.
But if you re-build style-spec, then maplibre-gl-js will fail to compile because of a broken import of operations.
This makes it hard to make any other changes to style-spec. (There are at least a couple of recent issues in gl-js that require changes in style-spec. I tried to work on them but it turned out impossible).

**Comment by HarelM** [comment]
I have a branch which solves this, you can work on that branch, or wait a bit.
I want to add the sky spec before releasing a new version...
