### ISSUE TITLE
The site needs search

### ISSUE THREAD

**Issue by micheal-w-wells** [maplibre/maplibre-style-spec#604]
# Design Proposal: Add search to docs site.

## Motivation

All good documentation sites include search.

## Proposed Change

Add a search toolbar.

## API Modifications

Possibly front end only but a great example are the godot docs.

## Migration Plan and Compatibility

No current search.

Make a statement about the compatibility of your new functionality with existing functionality.

**Comment by HarelM** [comment]
I'm not sure solidjs supports this. 
The only thing I could find is the following, which adds search to the solidjs docs site (which currently doesn't have search I believe):
https://github.com/solidjs/solid-docs-next/pull/622

Feel free to open a PR if you know differently.

**Comment by micheal-w-wells** [comment]
I'll take a stab at it when I have time.  Tried to stand up the app as per docs:

Node version wasn't mentioned, so I did`nvm use 20`, after seeing node 20 in package.json, then as per docs:
`cd docs && npm ci && npm run dev` but leads to `sh: vinxi: command not found`.

After `npm install` was able to run, but you just get a 404 every time.  I found SERVER_BASE_URL in a few places but exporting or putting `SERVER_BASE_URL='http://localhost:3000'` in a .env did not get me past the 404.

Can you point me in right direction?  I'll include updating the readme in PR if so.

**Comment by HarelM** [comment]
Have you tried the commands from here: 
https://github.com/maplibre/maplibre-style-spec/blob/main/.github/workflows/build-docs.yml
I think you might need to run some stuff outside the docs. 
CC: @birkskyum

**Comment by birkskyum** [comment]
Orama and algolia are quite big today. The solid docs recently added orama. These support fuzzy search

The mkdocs we have on gl js also has some local search but it needs an exact match

**Comment by HarelM** [comment]
What do you mean by extra match?

**Comment by birkskyum** [comment]
Exact match

**Comment by HarelM** [comment]
Ahh, yes, it misses fuzziness, yes.

**Comment by micheal-w-wells** [comment]
Hey guys thank you very much for adding search, super helpful!!

**Comment by HarelM** [comment]
NP, Enjoy!
