### ISSUE TITLE
Add docs how to serve docs locally

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-style-spec#618]
I ran

```
cd docs
npm install
npm run dev
```

But when I navigate to `http://localhost:3000/` I see 

```
{
  "statusCode": 404,
  "statusMessage": "Cannot find any path matching /.",
  "stack": []
}
```

We should add a readme at `docs/README.md`.

@birkskyum Could you help me out?

http://localhost:3000/maplibre-style-spec also does not work

**Comment by HarelM** [comment]
Did you try `npm run serve`? or `npm run build` and use a local http-server?
In any case, a readme won't hurt...
I usually look at the ci yaml code to understand what is done as part of the build...

**Comment by louwers** [comment]
Ah, works now. I didn't expect to need to run `npm run build` before `npm run dev`...
