### ISSUE TITLE
Remove macOS in support column

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-style-spec#645]
We don't have macOS releases, and there are no plans to have them again.

So I want to remove the macOS column in the support matrices.

**Comment by HarelM** [comment]
Enjoy.

**Comment by louwers** [comment]
@HarelM Do we use any kind of formatting for the style spec?

I want to edit it programmatically but when I write it out with `JSON.stringify` I see a lot of unrelated changes. If we don't have any formatting I would like to tackle that first.

**Comment by HarelM** [comment]
I'm not aware of any formatting, but you should only get white space changes, don't you?

**Comment by louwers** [comment]
No, many parts seem to be inconsistently formatted by hand.

**Comment by HarelM** [comment]
In the json file? What can be formatted by hand? 
In any case, feel free to format it...
