### ISSUE TITLE
Documentation for `image` source has minor typo to the radar GIF asset.

### ISSUE THREAD

**Issue by roblabs** [maplibre/maplibre-style-spec#658]
**Describe the bug**
Documentation for `image` source has minor typo to the radar GIF asset.  This makes the copy/paste feature of the documentation useless.  Fix for minor typo at https://github.com/maplibre/maplibre-style-spec/blob/1ebaa5a365df1502f2f99f5001697ff9409d3dfc/build/generate-docs.ts#L410

---

**Additional context**
This fix will allow those trying to add image sources to be able to use a real image.

**To Reproduce**
1. Go to https://maplibre.org/maplibre-style-spec/sources/#image
2. URL to radar GIF gives a 404; a minor typo in the path

        `404`:  https://maplibre.org/maplibre-gl-js-docs/assets/radar.gif
        works:  https://maplibre.org/maplibre-gl-js/docs/assets/radar.gif
                                                  ^^^

**Expected behavior**
URLs to real MapLibre assets should work.  If the example pointed to something arbitrary, E. G., `https://example.com/radar.gif`, we wouldn't fix.  

**Screenshots**

[<img  src="https://github.com/maplibre/maplibre-style-spec/assets/118112/5fef38fd-53c9-4f67-a5bc-8247882f75ef" width="61.8%"/>](https://github.com/maplibre/maplibre-style-spec/assets/118112/5fef38fd-53c9-4f67-a5bc-8247882f75ef)

**Comment by roblabs** [comment]
I would submit a PR, for this easy typo fix, but I can't get the `npm run mkdocs` to run successfully.

**Comment by HarelM** [comment]
Submit a PR, the CI will run the relevant check. 
I'll merge this.

**Comment by HarelM** [comment]
Fixed by #659
