### ISSUE TITLE
Remove confusing first line in the table of content

### ISSUE THREAD

**Issue by nyurik** [maplibre/maplibre-style-spec#707]
![image](https://github.com/maplibre/maplibre-style-spec/assets/1641515/7569388f-fa04-44ca-b7a6-af66dad729a0)

In this image, the first line in the table of content -- `MapLibre Style Spec` -- appears as if it is a topic, but cannot be clicked, and duplicates what is written right above it in the blue header. I tried to remove it, but not certain where it is. Thx!

**Comment by HarelM** [comment]
I could not find a configuration to remove this:
https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/

This is part of mkdocs material I believe. There might be a way to remove it using css, but I'm not sure it's worth the trouble, and might break in a later release...

**Comment by louwers** [comment]
Should be fine, since Material for MkDocs is built to be themed and customized.
