### ISSUE TITLE
Filter for BaseHeight and Height Comparison in Fill Extrusion Layer Causes Error

### ISSUE THREAD

**Issue by NasimAwabdy** [maplibre/maplibre-style-spec#723]
Summary:
There is an issue when attempting to filter features in a fill extrusion layer based on the comparison between baseHeight and height properties. The current filter expression results in an error indicating that a string, number, or boolean was expected, but an array was found.

Steps to Reproduce:
- Add a fill extrusion layer to the map.
- Attempt to filter out features where baseHeight is equal to height using the following filter:
`['!=',['get', 'baseHeight'], ['get', 'height']]`
- Observe the error: layers.d-furniture-extrusion.hot.filter[8][2]: string, number, or boolean expected, array found.

Expected Behavior:
The filter should correctly exclude features where baseHeight is equal to height.

Actual Behavior:
An error is thrown, indicating that the filter expression is not valid because it expects a string, number, or boolean, but finds an array.

Example Code : 
```
map.on('load', function () {
    map.addLayer({
        'id': '3d-buildings',
        'source': 'composite',
        'source-layer': 'building',
        'filter': [
            '!=', ['get', 'baseHeight'], ['get', 'height']
        ],
        'type': 'fill-extrusion',
        'minzoom': 15,
        'paint': {
            'fill-extrusion-color': '#aaa',
            'fill-extrusion-height': ['get', 'height'],
            'fill-extrusion-base': ['get', 'baseHeight'],
            'fill-extrusion-opacity': 0.6
        }
    });
});
```

Workaround:
A possible workaround involves adding a custom property sameHeight to the data source that flags whether baseHeight and height are equal, and then using this property for filtering.

1. Preprocess your data to include a sameHeight flag:
Update your data source to include a new property, e.g., sameHeight, which is true if baseHeight and height are the same, otherwise false.

```
map.on('load', function () {
    map.addLayer({
        'id': '3d-buildings',
        'source': 'composite',
        'source-layer': 'building',
        'filter': ['==', ['get', 'sameHeight'], false],
        'type': 'fill-extrusion',
        'minzoom': 15,
        'paint': {
            'fill-extrusion-color': '#aaa',
            'fill-extrusion-height': ['get', 'height'],
            'fill-extrusion-base': ['get', 'baseHeight'],
            'fill-extrusion-opacity': 0.6
        }
    });
});
```

**Comment by HarelM** [comment]
Thanks for taking the time to create the issue!
Can you create a reproduction please? It is not clear what part of the data is stored in the tiles and what exactly is not working as expected....

**Comment by NasimAwabdy** [comment]
Thank you for the quick reply, i will move this issue to the maplibre gl js repo and include a clear reproduction

**Comment by NasimAwabdy** [comment]
Thank you for the quick reply, i will move this issue to the maplibre gl js and include a clear reproduction

**Comment by NasimAwabdy** [comment]
Thank you for the quick reply, i will move this issue to the maplibre gl js and include a clear reproduction
