### ISSUE TITLE
`line-gradient` with data-driven styling

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-style-spec#740]
https://maplibre.org/maplibre-style-spec/layers/#line-gradient

@HarelM This seems to be supported for MapLibre GL JS. https://maplibre.org/maplibre-gl-js/docs/examples/line-gradient/

<img width="791" alt="image" src="https://github.com/maplibre/maplibre-style-spec/assets/649392/cbbf828d-12ee-4eae-b7b1-af1dd2058965">

It is not for MapLibre Native https://github.com/maplibre/maplibre-native/issues/2582

**Comment by HarelM** [comment]
The example is "hard coded" steps line gradient, I'm not sure it supports getting values from features, do you have an example of a featured based values that are used inside line-gradient?
Am I misinterpreting the definition of data-driven?

**Comment by louwers** [comment]
No I think I just misunderstood. Thanks. :)

**Comment by louwers** [comment]
Maybe interpolation doesn't work for MapLibre Native. I will look into it.
