### ISSUE TITLE
String expressions operate on UTF-16 code units instead of characters

### ISSUE THREAD

**Issue by 1ec5** [maplibre/maplibre-style-spec#778]
The TypeScript reference implementations of various string expression operators operate on [UTF-16 code units](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#utf-16_characters_unicode_code_points_and_grapheme_clusters) instead of full Unicode characters. This is most apparent when a string contains a character outside the Basic Multilingual Plane (BMP): that character is represented by a surrogate pair of two UTF-16 code units, but the expression operators split the surrogate pair in half.

## Examples

[This example](https://jsbin.com/juvabap/5/edit?html,output) contains two symbol layers that display the length and name, respectively, of a point feature in a GeoJSON source. The latter symbol layer is filtered to only features that contain “市镇” (meaning “town”) at the zero-based index of 2.

Two labels should appear, reading “4” and “丐𦨭市镇”. However, only one label appears, reading “5”.

<img src="https://github.com/user-attachments/assets/65b5af1b-a43a-47fa-91d2-1040be273f6a" width="400" alt="The number 5 all alone.">

This is because JavaScript stores 𦨭 (U+26A2D) as two UTF-16 code units: `D85A DE2D`.

For a more complex example, OpenStreetMap Americana labels place names in both the user’s preferred language and the prevailing local language. To avoid clutter, it applies some heuristics to deduplicate matching names between the two languages (ignoring diacritics when comparing against English). This requires a find-and-replace operation, but since maplibre/maplibre-gl-js#2064 and maplibre/maplibre-gl-js#2059 were both declined, the application includes [some complex subexpressions](https://github.com/osm-americana/openstreetmap-americana/blob/f9a8682ea7f24e4ec604b8a2199c17f0fec0832d/src/constants/label.js#L329-L401) that depend on `length`. This works fine now but will begin to return bizarre results once maplibre/maplibre-gl-js#4550 lands, even among strings that don’t contain any surrogate pairs.

Before | After
:--:|:--:
[<img src="https://github.com/user-attachments/assets/48a4ce43-2812-47c7-a8ab-d29bc3dd90e3" width="400" alt="则拉市镇 (Chợ Lách)">](https://americanamap.org/#map=12/10.25458/106.13179&language=zh)<br>[则拉市镇 (Chợ Lách)](https://www.openstreetmap.org/node/369490118) | <img src="https://github.com/user-attachments/assets/720d1ec3-9544-4fcc-ac40-20c27a15aec4" width="400" alt="则拉市镇 (则hợ Lách"><br>[则拉市镇 (则hợ Lách](https://www.openstreetmap.org/node/369490118)

## Impact

Until now, the impact would’ve been minimal, because GL JS has avoided rendering any codepoint beyond U+FFFF that would require surrogate pairs. The filters and properties would’ve evaluated incorrectly for any affected feature, but that would’ve been less noticeable than the abridged label for the same feature. However, maplibre/maplibre-gl-js#4550 would implement support for rendering non-BMP characters, making this issue more noticeable.

## Platform information

This issue reproduces in GL JS v4.5.2 but has probably been present ever since expressions were first implemented. The native implementation is even less intuitive, counting individual bytes: maplibre/maplibre-native#2730.

## Diagnosis

The implementations of these expression operators use traditional `String` methods that operate on UTF-16 code units. As in maplibre/maplibre-gl-js#4550, they need to be replaced with a [string iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Symbol.iterator).

https://github.com/maplibre/maplibre-style-spec/blob/76aabe5d6e586872db1a208ab32b6a9197868bf2/src/expression/definitions/length.ts#L35-L36 https://github.com/maplibre/maplibre-style-spec/blob/76aabe5d6e586872db1a208ab32b6a9197868bf2/src/expression/definitions/slice.ts#L65 https://github.com/maplibre/maplibre-style-spec/blob/76aabe5d6e586872db1a208ab32b6a9197868bf2/src/expression/definitions/index_of.ts#L69

**Comment by HarelM** [comment]
Feel free to submit a PR to fix this, I'm pretty sure you have the right knowledge, and I'm pretty sure I don't... :-)
