### ISSUE TITLE
`"in-range"` expression to enable more efficient indoor displays

### ISSUE THREAD

**Issue by CommanderStorm** [maplibre/maplibre-style-spec#796]
# Design Proposal: `in-range` expression

Before I start, I know this is somewhat of a niche usecase and the alternatives noted below are likely "good enough, but not coorect".

I can work on this, if you want ^^

## Motivation

While working on displaying indoor maps via [`map-gl-indoor`](https://github.com/map-gl-indoor/map-gl-indoor)[^1] I came across several things which are pretty hard to style.

Lets back up and talk about what the `level` tag allows for the following:
- *Unit*s e.g. `1`, `2`
- *Range*s e.g. `-2--1`, `0-4`
- *Union*s e.g. `2;4`, `1;5;3`, `1`
- all with postive and negative numbers

A few of the peculiarities of that schema are best dealt with at ingestion time:
- people like to insert semi-random spacing
- separating `unions` into separate features.
  Handling expressions over arrays is not possible in the current style shema unless hardcoding array lenghts is "okay" (via the string slicing shenanigans mentioned below).
  I am not asking for that to change.
  Rationale: I would not know how further array functionality should work (maybe `split` and 
 `apply`?).
- Wrong range order (e.g. `0--2` should be written as `-2-0`)
- Changing *Unit*s into *Range*s (`1` becomes `1-1`)

One thing is however pretty hard to do 
- Handling ranges is currently somewhat expensive, if done correctly.
  The best handling that I could come up with based on `map-gl-indoor`'s work is:
  - "splice" the strings together as needed.
    For example `["slice", ["get", "level"], 0, ["index-of", "-", ["get", "level"]]]` gets the first number for the case where the first the start of the range is positive
  - convert them via `to-number` and compare if larger/smaller than the wanted level
  - repeat 2x, based on if the first item in the range is negative or positive [`(-x-+y)/(-x--y)`,`(x--y)/(x-y)`]
  - collect everythiing with `any`/`all`/`case` expressions into a monster.

Now add this code to every layer you want to add and I think you can see why this causes performance problems (supprisingly not crippling, good job there).
I have not looked deeper in how capable the style compiler currently is, but such optimistations are likely pretty hard to impossible.

## Proposed Change

I would like to add an explicite `["in-range", VALUE, RANGE_TO_PARSE]` expression.
This would be quite similar to the `==`-expressions.

## API Modifications

Adding a new expression, tests and docs.

## Migration Plan and Compatibility

Adding expressions should not impact existing
Future compatibility might include deprecation of the expression if it turns out that better ways exist.. the usual stuff.

## Rejected Alternatives

- Only handle Unions (`level`=`2;3`) in the frontend
  => store this as `;2;3;` and build an expression if something is in the 2nd floor via `["in", ";2;", ["get", "level"]]`

  This does however not allow showing ranges for half-floors (like a floor between `1` and `2` being `1.5`) or does halluicante them (depending on implementation).
- Send the data separated by layer
  Users somewhat expect the data to be avaliable faster and expect there to not be network requests to (pre)fetch individual layers. Instead, users expect switching `level`s to "just work"
  Also that logic (when should I prefetch what?) is likely pretty hard to get really right.

[^1]: there are some wild bugs in there making it not quite ready for production, but hey...

**Comment by CommanderStorm** [comment]
To be fair:
if you don't think `in-range` or the other mentioned alternative fits into the current expressions, I am likely fine with the *Union*-alternative.

I still would liked to discus if I am overlooking something or if futher array options above might sound like an interesting options to add on your side ^^

**Comment by HarelM** [comment]
I'm not sure I fully understand the `in-range` syntax you suggested and I'm not sure I fully relate to this use case.
I know `level` OSM value can be complicated (much like opening_hours for example), but I would expect the data processing to "normalize" this something that will be easier to parse in the client side, for example to convert `0--2` to `[-2. -1, 0]` so that this array can be manipulated more easily.
Can you please elaborate?

**Comment by CommanderStorm** [comment]
The problem with the solution proposed by you is that it does not cover half-floors.

But you gave me an excellent idea:
The main point why my apporoach is problematic is that parsing ranges is not that simple.
If I sanatise `level`s like `3;-1-5` to be just `level`=`-1>5`, that tremendously cleans up my logic.
Was too fixated on my problem to see that, thanks a ton ❤️
