### ISSUE TITLE
Remove sort-object

### ISSUE THREAD

**Issue by moonglum** [maplibre/maplibre-style-spec#829]
# Design Proposal: Remove sort-object

## Motivation

We have an override in our project for quite some time to use a more up-to-date version of set-value. The reason for that is [`sort-object`](https://www.npmjs.com/package/sort-object), which is a dependency of maplibre-style-spec that has not been updated in over five years. I looked into the code of maplibre-style-spec, and I can't find it used anywhere.

## Proposed Change

I propose removing this dependency, as it seems to be unused.

## API Modifications

No API Modification necessary.

**Comment by HarelM** [comment]
Feel free to open a PR.
If it passes CI then it's probably not needed...

**Comment by moonglum** [comment]
Thanks, @HarelM :bow: It passes all tests: https://github.com/maplibre/maplibre-style-spec/pull/830
