### ISSUE TITLE
Design Proposal: Add Roll

### ISSUE THREAD

**Issue by NathanMOlson** [maplibre/maplibre-style-spec#850]
# Design Proposal: Add Roll

## Motivation

I would like to be able to roll the camera (rotate it about the camera boresight).
https://github.com/maplibre/maplibre-gl-js/issues/4717
https://github.com/maplibre/maplibre-gl-js/pull/4780

## Proposed Change

I would like to add a field `roll` to the root style spec object. `roll` sets the camera roll angle in degrees, and joins its friends `pitch` and `bearing`.

## API Modifications

Root style spec gets a new `roll` field. `jumpTo()`, `easeTo()`, and `flyTo()` get `roll` added to their options. `Camera` gets a `setRoll()` method.

## Migration Plan and Compatibility

This is a pure extension. To achieve existing functionality, just leave roll undefined (default 0).

## Rejected Alternatives

I considered adding `roll` to the API but not to the style spec. Rejected because:

1. ~~`roll` is needed in style spec for render tests.~~
2. Similar fields `pitch` and `bearing` already exist in style spec

**Comment by HarelM** [comment]
I think this can be a good addition.
Feel free to push this forward.
Don't forget the diff part of the implementation here.
