### ISSUE TITLE
NPM module includes unnecessary files

### ISSUE THREAD

**Issue by nstringham** [maplibre/maplibre-style-spec#923]
**Describe the bug**
When installing `@maplibre/maplibre-gl-style-spec` from npm many files are downloaded that are not needed

**To Reproduce**
1. run `npm i @maplibre/maplibre-gl-style-spec`
2. Open `node_modules/@maplibre/maplibre-gl-style-spec` folder in preferred file system browsing tool
3. Observe unnecessary files

**Expected behavior**
The npm module should only contain the js files from the dist folder and a few other important things like package.json

**Screenshots**
![Image](https://github.com/user-attachments/assets/82c5d91f-ccd3-4eb0-8f87-ca415420bffe)

**Desktop:**
 - OS: Windows 11

**Additional context**
I am using maplibre/maplibre-gl-style-spec as a sub-dependency of azure-maps-control

**Comment by nstringham** [comment]
I think this problem can be solved by using a `.npmignore` ([see npm dcumentation](https://docs.npmjs.com/cli/v9/using-npm/developers#keeping-files-out-of-your-package))

**Comment by HarelM** [comment]
The following are the files selected for the package: 
https://github.com/maplibre/maplibre-style-spec/blob/40f6fe71dcb0b24527ad45e88c2648d3624c8d4e/package.json#L46

I guess it is related to sourcemaps to see the actually code etc.
I'm not sure I fully understand the problem. 

BTW, If you are using a windows machine for JavaScript development I advise to use WSL, its's a lot faster...

**Comment by HarelM** [comment]
I also don't see this here: 
https://unpkg.com/browse/@maplibre/maplibre-gl-style-spec@22.0.0/

Are you sure you are using the latest package and that your npm cache is cleared?

**Comment by nstringham** [comment]
Ope, it looks like my project is using version 19.3.3 my bad. Yeah it seems to be fixed in recent versions.
