### ISSUE TITLE
Add code coverage reporting in CI

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-style-spec#98]
There's a need to introduce code coverage here as well, this existed when this repo was part of the maplibre-gl-js but I guess the move happened before the fix in maplibre-gl-js and thus it is missing here.

**Comment by ovivoda** [comment]
@HarelM can you point out please to the way it used to work? Do we still have a commit history of that?

**Comment by HarelM** [comment]
See here:
https://github.com/maplibre/maplibre-gl-js/blob/77b2782ad11cf6aba90f366a11462f4ac62230b8/.github/workflows/test-all.yml#L62
